# Generated by Django 5.0 on 2023-12-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('value',), 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
