# Generated by Django 5.0 on 2023-12-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_rating_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('★☆☆☆☆', '1 star'), ('★★☆☆☆', '2 stars'), ('★★★☆☆', '3 stars'), ('★★★★☆', '4 stars'), ('★★★★★', '5 stars')]),
        ),
    ]
